### ISSUE TITLE
Support API Documentation Versioning

### ISSUE THREAD

**Issue by Mordil** [vapor/api-docs#1]
With Vapor 2.0 making significant changes to the API, it would be a good idea to support different versions of the API documentation.

**Comment by tanner0101** [comment]
We're hoping to get something like `api.vapor.codes/1.0` and `/2.0` working

**Comment by Mordil** [comment]
Yup, just making an issue for tracking purposes :)

**Comment by Mordil** [comment]
Closing as this has been supported for awhile
