### ISSUE TITLE
[API Docs] roadmap?

### ISSUE THREAD

**Issue by marc-medley** [vapor/api-docs#20]
The [api.vapor.codes](https://api.vapor.codes/) currently has only one package `PostgresNIO`.  This is substantially less than the `API Docs` packages that were available for Vapor 3.

Is the go forward intent to have `API Docs` (1) just be `PostgresNIO`, (2) to be phased out or (3) to have the various packages added again?

**Comment by vzsg** [comment]
The documentation is being migrated to AWS, and apparently it hasn't been smooth sailing.
You can read more about that [here](https://blog.vapor.codes/posts/api-docs-are-changing/).

TL;DR: While the team finishes this migration, the full version of the Vapor 4 docs is available at [legacy.api.vapor.codes](https://legacy.api.vapor.codes/).

**Comment by marc-medley** [comment]
Thanks for the info and [legacy.api.vapor.codes](https://legacy.api.vapor.codes/) link.

If the transition will still take some time (and a minor update to the [api.vapor.codes](https://api.vapor.codes/) landing page is possible), then adding this info to the landing page could help users during the transition time. For example ...

> Vapor API Docs [are in transition](https://blog.vapor.codes/posts/api-docs-are-changing/). While this transition is in process, the full version of the Vapor 4 docs is available at [legacy.api.vapor.codes](https://legacy.api.vapor.codes/).

**Comment by marc-medley** [comment]
.... or perhaps alternately have [api.vapor.codes](https://api.vapor.codes/) redirect to [legacy.api.vapor.codes](https://legacy.api.vapor.codes/) until [api.vapor.codes](https://api.vapor.codes/) is fully ready to go live.

As FYI, I raised this issue because the `api.vapor.codes` bookmarks in my own markdown notes were _broken_. Whereas a redirect from `api.vapor.codes` to `legacy.api.vapor.codes` would not have broken the bookmarks.

**Comment by 0xTim** [comment]
The URLs for everything are changing anyway because we're migrating to DocC. Hoping to start churning through the rest of the packages next week

**Comment by 0xTim** [comment]
I'm closing this out - [api.vapor.codes](https://api.vapor.codes/) now has all the packages on it, using DocC and actually kept up to date - I'll do a blog post on it this week
