### ISSUE TITLE
404 page is not working correctly

### ISSUE THREAD

**Issue by 0xTim** [vapor/api-docs#21]
Attempting to access old pages which results in a 403 - this should be a 404 to help link checkers and a better experience for users

**Comment by beastboym** [comment]
Hello, I am a student, I would like to make my first contribution to your project, if this problem is still relevant. Would it be possible to assign it to me?

**Comment by 0xTim** [comment]
@beastboym go for it!

**Comment by beastboym** [comment]
Hello, thanks for the attribution, could you give me a path that will display the 403 ?, I did not manage to see one

**Comment by vzsg** [comment]
Anything on api.vapor.codes that doesn't exist and should return a 404, returns a 403.
For example: [https://api.vapor.codes/hello](https://api.vapor.codes/hello).

**Comment by beastboym** [comment]
Hello, I would like to apologize for the absence of feedback for all this time.
I am currently in the middle of a social movement which takes place in my University and in the country in general, and I ended up forgetting.
I think it would be best to take the attribution away from me, so someone else can work on it.
