### ISSUE TITLE
API/Fluent: White text on white background

### ISSUE THREAD

**Issue by marc-medley** [vapor/api-docs#29]
### Describe the bug

White text on white background is not readable.

### To Reproduce

Go to [https://api.vapor.codes/fluent/documentation/fluent/](https://api.vapor.codes/fluent/documentation/fluent/)

### Expected behavior

Expect some contrast between the text and the background.

### Environment

* Vapor Framework version: current [https://api.vapor.codes/](https://api.vapor.codes/) website
* Vapor Toolbox version: N/A
* OS version: N/A

### Additional context 

Unknown if this is an issue on other api pages. A sampling of other API pages looked ok.

![Screenshot 2023-07-29 at 11 08 04 AM](https://github.com/vapor/api-docs/assets/15098151/0d99934d-9374-491a-95fc-0bb66f8d27d4)

**Comment by gwynne** [comment]
This has already been addressed; the API docs site will update shortly. For an example, see http://api.vapor.codes/postgreskit/documentation/postgreskit/, which has already updated
